name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  peerreview-ai:
    runs-on: ubuntu-latest
    steps:
      - name: PeerReview.ai
        uses: PeerReview-ai/agent@0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'gpt-3.5-turbo'
          review-type: 'full'
          allowed-repositories: '*'