# name: PeerReview
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   peer-review:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     steps:
#       - uses: adrianveracom/agent@setup
#         with:
#           api-key: ${{ secrets.PEERREVIEW_API_KEY }}
#           api-endpoint: https://api.getpeerreview.com
#           review-type: full  # optional: full, focused, or security
