name: PeerReview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: adrianveracom/agent@test/other
        with:
          api-key: ${{ secrets.PEERREVIEW_API_KEY }}
          api-endpoint: https://api.getpeerreview.com
          review-type: full  # optional: full, focused, or security
